### ISSUE TITLE
Request: Support thigh twist bones

### ISSUE THREAD

**Issue by mienaiKnife** [wikid24/ffxiv_mmd_tools_helper#13]
Hi, I'm interested in using an addon to convert armatures to make them compatible with MMD motions, although I am not interested in FFXIV models specifically. I was trying to use this addon to convert a model ripped from Baldur's Gate 3, but the MMD conversion step 11 doesn't work on my model, and I'm guessing that the reason why is because I wanted to keep the model's thigh twist bones, which I named 左足捩 and 右足捩. I think that it should theoretically be easier to get thigh twist bones working with an MMD motion in Blender than in MMD, so would you consider adding such a functionality to your addon? Here is the exact error code that I got while trying to run step 11 on my model: 

Python: Traceback (most recent call last):
  File "C:\Users\[User]\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ffxiv_mmd_tools_helper\bone_conversion.py", line 1100, in execute
    main(context)
  File "C:\Users\[User]\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ffxiv_mmd_tools_helper\bone_conversion.py", line 996, in main
    add_foot_leg_ik.clear_IK(context)
  File "C:\Users\[User]\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ffxiv_mmd_tools_helper\add_foot_leg_ik.py", line 46, in clear_IK
    bpy.context.view_layer.objects.active = get_armature()
  File "C:\Users\[User]\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ffxiv_mmd_tools_helper\add_foot_leg_ik.py", line 382, in get_armature
    if bpy.context.selected_objects[0].type == 'ARMATURE':
IndexError: list index out of range

**Comment by wikid24** [comment]
Hi @mienaiKnife , I created a excel smartsheet for translating bone names between different model structures

Feel free to add the BG3 bones to column E, and I will add this in the next update: https://docs.google.com/spreadsheets/d/1voXtYp4DAQrmPL1uCVINrL0_jbnZCOIqf-oaumsd3UE/edit?usp=sharing

Cheers!

**Comment by mienaiKnife** [comment]
Unfortunately, the BG3 models have bones in the arms and legs that are holding weight in weird places, which would make it hard to make them fully compatible with your addon. It's hard to explain, but I could try to send you a .blend file with a ripped model to illustrate my point. I did previously write a script to rename bones according to what weight they hold, but then I had to move them around manually to make sure they were where they're supposed to be in an MMD armature.

**Comment by wikid24** [comment]
sure, feel free attach it to the ticket and I'll check it out  :thumbsup:

**Comment by mienaiKnife** [comment]
Alright, here's Astarion with minimal editing:
[Astarion default redux.zip](https://github.com/user-attachments/files/15908633/Astarion.default.redux.zip)
Obviously there's quite a bit of editing that I would have to do by hand before I could use your addon to convert it to MMD.

**Comment by wikid24** [comment]
looked at the file, yeah I think the leg's weight painting is on armature.004? Hard to tell since there is 7 armatures in the file. 

Looking at the armature, a few things to keep in mind:

- All the lower body bones need to be connected together (bones won't move properly unless they are connected):

While in edit mode:
![image](https://github.com/wikid24/ffxiv_mmd_tools_helper/assets/19479648/6b53577f-9275-4823-b5c9-94afa1d77185)

parent/child relationship on the connected bones should be something like: 

- Waist -> leg -> Knee -> ankle -> toe

for the twist bone, it just needs to be a child of the correct bone it is twisting. Standard MMD animation files don't animate leg twist bones so it doesn't need to be included in the chain mentioned above. Best example I can give is using the FFXIV sample models (included in the plugin, renamed to MMD English), you can see an example of it on the arm twist bone:
![image](https://github.com/wikid24/ffxiv_mmd_tools_helper/assets/19479648/153d9cc9-b7a1-44d8-8f8b-80993ceb92f8)

After all the bones are connected you should have a functioning armature you can see moving in pose mode...  Then it would be a simple matter of renaming all the lower the leg bones to something MMD can recognize (such as the bone names on the google sheet I mentioned), and then the plugin should do its thing properly to create the IK leg stuff. 

After you clean it up into _one_ armature, if you're still having issues let me know

**Comment by wikid24** [comment]
Ah then you should check out the D bones in MMD armatures. They don't have any weight paint associated with them, they're special bones with a bone constraint that MMD Tools creates when you add these settings to it, 

Example of the leg_L_D bone which is an empty bone with no weight painting on it should do what you're looking for (also this plugin creates it when running the leg IK step) :
![image](https://github.com/wikid24/ffxiv_mmd_tools_helper/assets/19479648/e70243e7-63b0-401b-bc64-8883850263d9)

**Comment by mienaiKnife** [comment]
Normally, when I take an MMD model that has 足D bones (i.e. the leg_L_D bone when translated) and I import it into Blender, I can see that the 足D bone is the one holding the weight of the thigh and it's copying the rotation of the respective 足 bone in the IK chain. I was assuming that the purpose of it was to provide a sort of parallel FK chain for MMD animators, and that D stands for deform. Seems like you're conflating D bones with bones that have the Rotation+ append (appends are basically the equivalent of bone constraints in the pmx file format).

**Comment by wikid24** [comment]
do you have an example mmd model that you're using as a baseline?

**Comment by mienaiKnife** [comment]
Here's one: https://bowlroll.net/file/4576

**Comment by wikid24** [comment]
looks like a standard TDA MMD model, the D bone is setup with the same rotation constraint applied to mirror the leg bone, so if weight paint is on either one it will work fine. D bones are really used for those additional animation tweaks _after_ IK is applied

I'm sure you can definitely can do extra stuff within blender that you mentioned, but this plugin was designed around mimicking the TDA MMD armature structure since that is what is used by the VMD motion files. any additional IK/FK you're looking to do outside of those will probably mess with whatever the animator keyframed in the VMD files, so something to keep in mind

**Comment by mienaiKnife** [comment]
My goal is to make the deformation look good and accurate to how the model appears in the game without messing with whatever the animator keyframed in the VMD files.
